#include <iostream>
using namespace std;
int main() {
	string provinsi;
	string kabupaten;
	string NIK;
	string nama;
	string tempat_tanggal_lahir;
	string alamat;
	string jenis_kelamin;
	string RT_RW;
	string kelurahan;
	string kecamatan;
	string agama;
	string status_nikah;
	string pekerjaan;
	string kewarganegaraan;
	string masa_berlaku;
	cout<<"\n\nData KTP by EKO142";
	cout<<"\nSiapkan KTP dan INPUT DATA nya PERSIS";
	cout<<"\n\n";
	cout<<"Masukkan Provinsi : ";
	getline(cin,provinsi);
	cout<<"\n";
	cout<<"Masukkan Kabupaten : ";
	getline(cin,kabupaten);
	cout<<"\n";
	cout<<"Masukkan NIK : ";
	getline(cin,NIK);
	cout<<"\n";
	cout<<"Masukkan Nama : ";
	getline(cin,nama);
	cout<<"\n";
	cout<<"Masukkan Tempat/Tgl Lahir : ";
	getline(cin,tempat_tanggal_lahir);
	cout<<"\n";
	cout<<"Masukkan Jenis Kelamin :";
	getline(cin,jenis_kelamin);
	cout<<"\n";
	cout<<"Masukkan Alamat : ";
	getline(cin,alamat);
	cout<<"\n";
	cout<<"Masukkan RT/RW : ";
	getline(cin,RT_RW);
	cout<<"\n";
	cout<<"Masukkan Kelurahan/Desa : ";
	getline(cin,kelurahan);
	cout<<"\n";
	cout<<"Masukkan Kecamatan : ";
	getline(cin,kecamatan);
	cout<<"\n";
	cout<<"Masukkan Agama : ";
	getline(cin,agama);
	cout<<"\n";
	cout<<"Masukkan Status Perkawinan : ";
	getline(cin,status_nikah);
	cout<<"\n";
	cout<<"Masukkan Pekerjaan : ";
	getline(cin,pekerjaan);
	cout<<"\n";
	cout<<"Masukkan Kewarganegaraan : ";
	getline(cin,kewarganegaraan);
	cout<<"\n";
	cout<<"Masukkan Masa Berlaku : ";
	getline(cin,masa_berlaku);
	cout<<"\n\n";
	cout<<"==================================================\n";
	cout<<"\t\tPROVINSI\t"<<provinsi<<"\n";
	cout<<"\t\tKABUPATEN\t"<<kabupaten<<"\n";
	cout<<"\n";
	cout<<"NIK \t\t:"<<NIK<<"\n";
	cout<<"Nama \t\t\t:"<<nama<<"\n";
	cout<<"Tempat/Tgl Lahir \t:"<<tempat_tanggal_lahir<<"\n";
	cout<<"Jenis Kelamin \t\t:"<<jenis_kelamin<<"\n";
	cout<<"Alamat \t\t\t:"<<alamat<<"\n";
	cout<<"\tRT/RW \t\t:"<<RT_RW<<"\n";
	cout<<"\tKel/Desa \t:"<<kelurahan<<"\n";
	cout<<"\tKecamatan \t:"<<kecamatan<<"\n";
	cout<<"Agama \t\t\t:"<<agama<<"\n";
	cout<<"Status Perkawinan \t:"<<status_nikah<<"\n";
	cout<<"Pekerjaan \t\t:"<<pekerjaan<<"\n";
	cout<<"Kewarganegaraan \t:"<<kewarganegaraan<<"\n";
	cout<<"Berlaku Hingga \t\t:"<<masa_berlaku<<"\n";
	cout<<"\n\n";
	cout<<"==================================================\n";
	cout<<"Sekian Program Saya,Apabila ada salah Mohon Maaf\n";
	cout<<"\nEKO_UAD_2100018142\n";
	return 0;
	}
